import {
  Component,
  OnInit,
  ViewChild,
  AfterViewInit,
  Renderer,
  Renderer2,
} from '@angular/core';
import {
  CdkDragDrop,
  moveItemInArray,
  CdkDragStart,
  CdkDragRelease,
} from '@angular/cdk/drag-drop';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  columns: any[];
  paginateData: any[];
  pos: any;
  release: boolean = true;

  constructor(public renderer: Renderer, public renderer2: Renderer2) {}

  options = [
    {
      _id: '633b156ea642c800362b08d2',
      key: 'shipmentId',
      display: true,
    },
    {
      _id: '633b156ea642c800362b08d3',
      key: 'referenceName',
      display: true,
    },
    {
      _id: '633b156ea642c800362b08d4',
      key: 'tags',
      display: true,
    },
    {
      _id: '633b156ea642c800362b08d5',
      key: 'freightType',
      display: true,
    },
    {
      _id: '633b156ea642c800362b08d6',
      key: 'etd',
      display: true,
    },
    {
      _id: '633b156ea642c800362b08d7',
      key: 'eta',
      display: true,
    },
    {
      _id: '633b156ea642c800362b08d8',
      key: 'notes',
      display: true,
    },
  ];

  ngOnInit() {
    this.columns = this.options.map(({ key }) => ({ field: key, header: key }));
    /* this.columns = [
                {"field": "_id", "header": "Id"},
                {"field": "firstName", "header": "First Name"},
                {"field": "lastName", "header": "Last Name"},
                {"field": "Address", "header": "Address"},
                {"field": "street", "header": "Street"},
                {"field": "city", "header": "City"},
                {"field": "state", "header": "State"}
            ]  */
    /* this.paginateData = [
      {
        _id: '1',
        firstName: 'Becker',
        lastName: 'Glenn',
        Address: 626,
        street: 'Keap Street',
        city: 'Oceola',
        state: 'Tennessee',
      },
      {
        _id: '2',
        firstName: 'Kellie',
        lastName: 'Moody',
        Address: 426,
        street: 'Windsor Place',
        city: 'Condon',
        state: 'Minnesota',
      },
    ]; */
    this.paginateData = [
      {
        _id: '62dabc269cae2a03d0eb49b8',
        milestones: [],
        tags: ['upcoming'],
        tenantId: 'Shipment-rokk3r',
        bookingId: 'B562-285_BERN-NUEVA_CLOCK_OSCILLATORS-5',
        companyId: '5e5893ef851e34004b7f954f',
        referenceName: 'Clocks',
        quoteId: '624c63c6f39a4d0035ee4932',
        manualInput: true,
        fullName: 'prueba3',
        shipper: 'prueba3',
        consignee: 'prueba3',
        agent: 'prueba3',
        carrier: {
          _id: '6019c700e3e6248a7fd73cb5',
          name: 'CMA CGM',
          type: 'carrier',
          group: 'sea',
          logo: 'https://storage.googleapis.com/carriers_logos/CMA-CGM.png',
          logo2x:
            'https://storage.googleapis.com/carriers_logos/CMA-CGM%402x.png',
          cursor: 362,
          __v: 0,
          createdAt: '2021-01-29T21:58:41.246Z',
          updatedAt: '2021-01-29T21:58:41.246Z',
          scac: ['CMDU', 'CMAU', 'CMDUAAA', 'CMAUAAA'],
        },
        origin: 'Bern, Switzerland',
        destination: 'Nueva York, NY, USA',
        arrivalDate: '2022-07-26T05:00:00.000Z',
        etd: '2022-07-26T05:00:00.000Z',
        timeOfTransit: '4',
        currentStatus: 'upcoming',
        currentMilestone: 'Origin',
        attachments: [],
        vesselNumber: 'TTT',
        cutoff: '2022-07-28T05:00:00.000Z',
        confirmationNumber: 'TTT',
        containers: [],
        mbl: 'TTTgg',
        flightNumber: '',
        booking: {
          shipper: {
            name: 'prueba3',
            address: 'Chicago, Illinois, EE. UU.',
            email: 'prueba3@gmail.com',
            phone: '+573197744545',
          },
          notify: {
            name: 'prueba3',
            address: 'Chicago, Illinois, EE. UU.',
            email: 'prueba3@gmail.com',
            phone: '+573197744545',
          },
          consignee: {
            name: 'prueba3',
            address: 'Chicago, Illinois, EE. UU.',
            email: 'prueba3@gmail.com',
            phone: '+573197744545',
          },
          agent: {
            name: 'prueba3',
            address: 'Chihuahua, Chih., México',
            email: 'prueba3@gmail.com',
            phone: '+573155474454',
          },
          shipmentDetails: {
            originDetails: {
              lat: 46.9479739,
              lng: 7.4474468,
              countryCode: 'CH',
            },
            destinationDetails: {
              lat: 40.7127753,
              lng: -74.0059728,
              countryCode: 'US',
            },
            origin: 'Bern, Switzerland',
            destination: 'Nueva York, NY, USA',
            accessorials: [],
          },
          shippingInstructions: {
            vesselNumber: 'TTT',
            carrier: {
              _id: '6019c700e3e6248a7fd73cb5',
              name: 'CMA CGM',
              type: 'carrier',
              group: 'sea',
              logo: 'https://storage.googleapis.com/carriers_logos/CMA-CGM.png',
              logo2x:
                'https://storage.googleapis.com/carriers_logos/CMA-CGM%402x.png',
              cursor: 362,
              __v: 0,
              createdAt: '2021-01-29T21:58:41.246Z',
              updatedAt: '2021-01-29T21:58:41.246Z',
              scac: ['CMDU', 'CMAU', 'CMDUAAA', 'CMAUAAA'],
            },
            etd: '2022-07-26T05:00:00.000Z',
            cutoff: '2022-07-28T05:00:00.000Z',
            confirmationNumber: 'TTT',
            containers: [],
            mbl: 'TTT',
            flightNumber: '',
          },
          tags: ['in progress'],
          tenantId: 'Booking-rokk3r',
          _id: '62c5ba8b07ae9200bd46d208',
          quoteId: '624c63c6f39a4d0035ee4932',
          referenceName: 'Clocks',
          dateRequested: '2022-07-06T16:37:45.301Z',
          companyId: '5e5893ef851e34004b7f954f',
          dateExpired: null,
          price: 1108.08,
          quote: {
            _id: '624c63c6f39a4d0035ee4932',
            quoteReply: {
              currency: 'USD',
              portOrigin: '',
              portDestination: '',
              setPrice: {
                user: 'Jairo Internal',
                _id: '5ea1b0cbb5775f01b50ac1e5',
                date: '2022-04-05T15:44:24.993Z',
              },
              validity: null,
              message: null,
              rate: {
                transportationMode: {
                  value: 'ship',
                  type: 'keyValue',
                },
                shipmentType: {
                  value: 'FCL',
                  type: 'keyValue',
                },
                commodity: {
                  value: 'Clock oscillators',
                  type: 'keyValue',
                },
                countryOrigin: {
                  value: null,
                  type: 'keyValue',
                },
                cityOrigin: {
                  value: 'Bern, Switzerland',
                  type: 'keyValue',
                },
                countryDestination: {
                  value: null,
                  type: 'keyValue',
                },
                cityDestination: {
                  value: 'Nueva York, NY, USA',
                  type: 'keyValue',
                },
                portOrigin: {
                  value: null,
                  type: 'keyValue',
                },
                portDestination: {
                  value: null,
                  type: 'keyValue',
                },
                twenty: {
                  value: 9,
                  type: 'freight',
                },
                fourty: {
                  value: 9,
                  type: 'freight',
                },
                fourtyFive: {
                  value: 9,
                  type: 'freight',
                },
                fourtyHC: {
                  value: 9,
                  type: 'freight',
                },
                fourtyRF: {
                  value: 9,
                  type: 'freight',
                },
                fourtyNOR: {
                  value: 9,
                  type: 'freight',
                },
                tho: {
                  value: 8,
                  type: 'freightSurcharges',
                },
                thd: {
                  value: 7,
                  type: 'freightSurcharges',
                },
                fob: {
                  value: 8,
                  type: 'freightSurcharges',
                },
                tt: {
                  value: null,
                  type: 'info',
                },
                ebs: {
                  value: 76,
                  type: 'freightSurcharges',
                },
                transhipment: {
                  value: null,
                  type: 'info',
                },
                prepaidPerContainer: {
                  value: 7,
                  type: 'taxes',
                },
                collectPerContainer: {
                  value: 65,
                  type: 'taxes',
                },
                localChargesPerShipment: {
                  value: 65,
                  type: 'taxes',
                },
                localChargesHazardous: {
                  value: 6,
                  type: 'taxes',
                },
                localChargesFoodGrade: {
                  value: 4,
                  type: 'taxes',
                },
                customBrokerageImport: {
                  value: null,
                  type: 'taxes',
                },
                customBrokerageExport: {
                  value: 567,
                  type: 'taxes',
                },
                controlFeeForwarder: {
                  value: 9,
                  type: 'freight',
                },
                controlFeeAgent: {
                  value: 909,
                  type: 'freight',
                },
                tax: {
                  value: 8,
                  type: 'taxes',
                },
                sealineAirline: {
                  value: 'MSC',
                  type: 'info',
                },
                frequency: {
                  value: null,
                  type: 'info',
                },
                freeDaysAtDestination: {
                  value: null,
                  type: 'info',
                },
                notes: {
                  value: null,
                  type: 'info',
                },
                validity: {
                  value: '2022-04-30T05:00:00.000Z',
                  type: 'keyValue',
                },
                validityFrom: {
                  value: '2022-04-01T05:00:00.000Z',
                  type: 'keyValue',
                },
                tenantId: 'Rate-rokk3r',
                _id: '624c6236f39a4d0035ee4801',
                kind: 'ship FCL',
                showFreightSurchargesDetails: false,
                showTaxesDetails: false,
                extraFields: [],
                updatedAt: '2022-04-05T15:37:26.663Z',
                createdAt: '2022-04-05T15:37:26.663Z',
                __v: 0,
                line: {
                  _id: '6019c700e3e6248a7fd73cae',
                  name: 'MSC',
                  type: 'carrier',
                  group: 'sea',
                  cursor: 360,
                  logo: 'https://storage.googleapis.com/carriers_logos/msc-logo.png',
                  logo2x:
                    'https://storage.googleapis.com/carriers_logos/msc-logo2x.png',
                  __v: 0,
                  createdAt: '2021-01-29T21:58:41.246Z',
                  updatedAt: '2021-01-29T21:58:41.246Z',
                  scac: ['MSCU', 'MEDU', 'MSCUAA', 'MEDUAA'],
                },
                freight: 927,
                freightSurcharges: 99,
                localCharges: 82.08,
                price: 1108.08,
              },
              quoteDetails: [
                {
                  _id: '624c63dcf39a4d0035ee4937',
                  sectionName: 'details',
                  price: 1108.08,
                  itemsData: [
                    {
                      _id: '624c63dcf39a4d0035ee4938',
                      price: 927,
                      item: 'Freight',
                      details: '',
                      USDprice: 927,
                    },
                    {
                      _id: '624c63dcf39a4d0035ee4939',
                      price: 99,
                      item: 'Freight Surcharges',
                      details: '',
                      USDprice: 99,
                    },
                    {
                      _id: '624c63dcf39a4d0035ee493a',
                      price: 82.08,
                      item: 'Shipment Fees',
                      details: '',
                      USDprice: 82.08,
                    },
                  ],
                  USDprice: 1108.08,
                },
              ],
              transitTimeFrecuency: 'days',
              transitTime: null,
              totalCost: 1108.08,
              carrier: {
                name: 'MSC',
              },
              USDtotalCost: 1108.08,
            },
            tags: ['active'],
            tenantId: 'Quote-rokk3r',
            companyId: '5e5893ef851e34004b7f954f',
            nameOfQuote: 'Clocks',
            quoteHash: '947bd558-6496-4774-afbf-ee90d115defc',
            commodity: 'Clock oscillators',
            commodityDescription: null,
            incoterms: 'FCA',
            transportationMode: 'ship',
            shipmentType: 'FCL',
            paymentTerms: 'prepaid',
            truckingService: 0,
            truckingServiceOption: null,
            truckingServiceOrigin: {
              pickupAddress: null,
            },
            truckingServiceDestiny: {
              deliveryAddress: null,
            },
            origin: 'Bern, Switzerland',
            destination: 'Nueva York, NY, USA',
            customBrokerage: 0,
            urgentShipment: 0,
            specialInstructions: null,
            portOrigin: null,
            portDestination: null,
            totalWeight: null,
            totalVolume: null,
            volumeType: 'm',
            weightType: 'kg',
            packagingData: [
              {
                amount: '1',
                volume: null,
                weight: null,
                totalVolume: null,
                totalWeight: null,
                lengthType: 'in',
                weightType: 'lb',
                hazardousMaterials: 0,
                hazardousDetails: [
                  {
                    class: null,
                    subdivision: null,
                    group: null,
                    attach: null,
                  },
                ],
                refrigeration: 0,
                containerType: "Dry 20'",
              },
            ],
            disclaimers: [
              {
                _id: '61d5a453b758410035c59806',
                title: 'v',
                description: 'f',
              },
              {
                _id: '61329d01a7df0d00355a1fb1',
                title: 'Blah!',
                description:
                  "\nWhy do we use it?\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\n\n",
              },
              {
                _id: '60c395fd6edb4e0035cc45e2',
                title: 'Importaciones',
                description: 'Requiere contrato',
              },
            ],
            owner: {
              user: 'Jairo Internal',
              idUser: '5ea1b0cbb5775f01b50ac1e5',
              email: 'jairo.mendoza+rokk3r-ff@rokk3rlabs.com',
              typeUser: 'internal-owner',
              companyName: 'Rokk3r Clients',
              idCompany: '5e5893ef851e34004b7f954f',
            },
            accessorials: [],
            attachments: [],
            dimensionsPerPackage: [],
            __v: 0,
            assignData: {
              fromUser: {
                jobTitle: 'ceo',
                uid: '5ea1b0ca257713002656d92b',
                firstName: 'Jairo Internal',
                _id: '5ea1b0cbb5775f01b50ac1e5',
                email: 'jairo.mendoza+rokk3r-ff@rokk3rlabs.com',
              },
              user: {
                jobTitle: null,
                uid: '5ee33ad3c47179003a38b065',
                sendEmail: false,
                urlPhotoProfile:
                  'https://storage.googleapis.com/development_app_files/rokk3r/profiles/b505b526-93c0-9922-3060-f5d809b2b780.jpg',
                firstName: 'Nata',
                _id: '5ee33ad356d39f0173524c2d',
                email: 'natalia.castellanos+rokk3r-ff-2@rokk3rlabs.com',
              },
              message: 'TYU',
              date: '2022-04-05T15:35:08.963Z',
              closeAssignDate: '2022-04-05T15:37:36.201Z',
              closeAssignMessage: '',
              internalAssigned: {
                jobTitle: 'ceo',
                uid: '5ea1b0ca257713002656d92b',
                sendEmail: true,
                firstName: 'Jairo Internal',
                _id: '5ea1b0cbb5775f01b50ac1e5',
                email: 'jairo.mendoza+rokk3r-ff@rokk3rlabs.com',
              },
            },
            confirmation: {
              aprovedBy: '5ea1b0cbb5775f01b50ac1e5',
              date: '2022-04-05T20:34:35.836Z',
              status: 'accept',
              fileId: '624ca7d9ebecd4002421e69d',
              description: 'ewrwerew',
            },
            clonedFrom: 'Q559-285_BERN-NUEVA_CLOCK_OSCILLATORS',
            status: 4,
            quoteId: 'Q562-285_BERN-NUEVA_CLOCK_OSCILLATORS',
            alterTags: {
              active: true,
            },
            updatedAt: '2022-04-05T20:34:35.911Z',
            createdAt: '2022-04-05T15:44:06.391Z',
            cursor: 910,
            trade: 'export',
            destinationDetails: {
              lng: 40.7127753,
              lat: -74.0059728,
              countryCode: 'US',
            },
            originDetails: {
              lng: 46.9479739,
              lat: 7.4474468,
              countryCode: 'CH',
            },
            createdDays: 92,
            company: 'rokk3r-clients',
          },
          packagingData: [
            {
              amount: '1',
              volume: null,
              weight: null,
              totalVolume: null,
              totalWeight: null,
              lengthType: 'in',
              weightType: 'lb',
              hazardousMaterials: 0,
              hazardousDetails: [
                {
                  class: null,
                  subdivision: null,
                  group: null,
                  attach: null,
                },
              ],
              refrigeration: 0,
              containerType: "Dry 20'",
            },
          ],
          validity: '2021-08-25T00:00:00.000Z',
          frequencyOfTrips: 3,
          timeToTransit: 4,
          owner: {
            user: 'Nata',
            idUser: '5ee33ad356d39f0173524c2d',
            email: 'natalia.castellanos+rokk3r-ff-2@rokk3rlabs.com',
            typeUser: 'internal-owner',
            companyName: 'Rokk3r Clients',
            idCompany: '5e5893ef851e34004b7f954f',
          },
          status: 'inProgress',
          alterTags: {
            'in progress': true,
          },
          USDprice: 1108.08,
          bookingId: 'B562-285_BERN-NUEVA_CLOCK_OSCILLATORS-5',
          history: {
            shipmentDetails: {
              originDetails: {
                lat: [
                  {
                    previousValue: 7.4474468,
                    currentValue: 46.9479739,
                    time: '2022-07-06T16:38:35.844Z',
                    updatedBy: {
                      email: 'natalia.castellanos+rokk3r-ff-2@rokk3rlabs.com',
                      firstName: 'Nata',
                      _id: '5ee33ad356d39f0173524c2d',
                      uid: '5ee33ad3c47179003a38b065',
                    },
                  },
                ],
                lng: [
                  {
                    previousValue: 46.9479739,
                    currentValue: 7.4474468,
                    time: '2022-07-06T16:38:35.845Z',
                    updatedBy: {
                      email: 'natalia.castellanos+rokk3r-ff-2@rokk3rlabs.com',
                      firstName: 'Nata',
                      _id: '5ee33ad356d39f0173524c2d',
                      uid: '5ee33ad3c47179003a38b065',
                    },
                  },
                ],
                formattedAddress: [
                  {
                    currentValue: 'Bern, Switzerland',
                    time: '2022-07-06T16:38:35.845Z',
                    updatedBy: {
                      email: 'natalia.castellanos+rokk3r-ff-2@rokk3rlabs.com',
                      firstName: 'Nata',
                      _id: '5ee33ad356d39f0173524c2d',
                      uid: '5ee33ad3c47179003a38b065',
                    },
                  },
                ],
                country: [
                  {
                    currentValue: 'Switzerland',
                    time: '2022-07-06T16:38:35.845Z',
                    updatedBy: {
                      email: 'natalia.castellanos+rokk3r-ff-2@rokk3rlabs.com',
                      firstName: 'Nata',
                      _id: '5ee33ad356d39f0173524c2d',
                      uid: '5ee33ad3c47179003a38b065',
                    },
                  },
                ],
              },
              destinationDetails: {
                lat: [
                  {
                    previousValue: -74.0059728,
                    currentValue: 40.7127753,
                    time: '2022-07-06T16:38:35.845Z',
                    updatedBy: {
                      email: 'natalia.castellanos+rokk3r-ff-2@rokk3rlabs.com',
                      firstName: 'Nata',
                      _id: '5ee33ad356d39f0173524c2d',
                      uid: '5ee33ad3c47179003a38b065',
                    },
                  },
                ],
                lng: [
                  {
                    previousValue: 40.7127753,
                    currentValue: -74.0059728,
                    time: '2022-07-06T16:38:35.845Z',
                    updatedBy: {
                      email: 'natalia.castellanos+rokk3r-ff-2@rokk3rlabs.com',
                      firstName: 'Nata',
                      _id: '5ee33ad356d39f0173524c2d',
                      uid: '5ee33ad3c47179003a38b065',
                    },
                  },
                ],
                formattedAddress: [
                  {
                    currentValue: 'Nueva York, NY, USA',
                    time: '2022-07-06T16:38:35.847Z',
                    updatedBy: {
                      email: 'natalia.castellanos+rokk3r-ff-2@rokk3rlabs.com',
                      firstName: 'Nata',
                      _id: '5ee33ad356d39f0173524c2d',
                      uid: '5ee33ad3c47179003a38b065',
                    },
                  },
                ],
                country: [
                  {
                    currentValue: 'United States',
                    time: '2022-07-06T16:38:35.847Z',
                    updatedBy: {
                      email: 'natalia.castellanos+rokk3r-ff-2@rokk3rlabs.com',
                      firstName: 'Nata',
                      _id: '5ee33ad356d39f0173524c2d',
                      uid: '5ee33ad3c47179003a38b065',
                    },
                  },
                ],
              },
            },
            packagingData: {
              'hazardousDetails-1': [
                {
                  previousValue: [
                    {
                      class: null,
                      subdivision: null,
                      group: null,
                      attach: null,
                    },
                  ],
                  currentValue: [
                    {
                      class: null,
                      subdivision: null,
                      group: null,
                      attach: null,
                    },
                  ],
                  time: '2022-07-06T16:38:35.847Z',
                  updatedBy: {
                    email: 'natalia.castellanos+rokk3r-ff-2@rokk3rlabs.com',
                    firstName: 'Nata',
                    _id: '5ee33ad356d39f0173524c2d',
                    uid: '5ee33ad3c47179003a38b065',
                  },
                },
              ],
            },
          },
          priceBreakdown: [],
          attachments: [],
          updatedAt: '2022-07-06T16:38:35.911Z',
          createdAt: '2022-07-06T16:38:35.911Z',
          cursor: 408,
          __v: 0,
        },
        quote: {
          _id: '624c63c6f39a4d0035ee4932',
          quoteReply: {
            currency: 'USD',
            portOrigin: '',
            portDestination: '',
            setPrice: {
              user: 'Jairo Internal',
              _id: '5ea1b0cbb5775f01b50ac1e5',
              date: '2022-04-05T15:44:24.993Z',
            },
            validity: null,
            message: null,
            rate: {
              transportationMode: {
                value: 'ship',
                type: 'keyValue',
              },
              shipmentType: {
                value: 'FCL',
                type: 'keyValue',
              },
              commodity: {
                value: 'Clock oscillators',
                type: 'keyValue',
              },
              countryOrigin: {
                value: null,
                type: 'keyValue',
              },
              cityOrigin: {
                value: 'Bern, Switzerland',
                type: 'keyValue',
              },
              countryDestination: {
                value: null,
                type: 'keyValue',
              },
              cityDestination: {
                value: 'Nueva York, NY, USA',
                type: 'keyValue',
              },
              portOrigin: {
                value: null,
                type: 'keyValue',
              },
              portDestination: {
                value: null,
                type: 'keyValue',
              },
              twenty: {
                value: 9,
                type: 'freight',
              },
              fourty: {
                value: 9,
                type: 'freight',
              },
              fourtyFive: {
                value: 9,
                type: 'freight',
              },
              fourtyHC: {
                value: 9,
                type: 'freight',
              },
              fourtyRF: {
                value: 9,
                type: 'freight',
              },
              fourtyNOR: {
                value: 9,
                type: 'freight',
              },
              tho: {
                value: 8,
                type: 'freightSurcharges',
              },
              thd: {
                value: 7,
                type: 'freightSurcharges',
              },
              fob: {
                value: 8,
                type: 'freightSurcharges',
              },
              tt: {
                value: null,
                type: 'info',
              },
              ebs: {
                value: 76,
                type: 'freightSurcharges',
              },
              transhipment: {
                value: null,
                type: 'info',
              },
              prepaidPerContainer: {
                value: 7,
                type: 'taxes',
              },
              collectPerContainer: {
                value: 65,
                type: 'taxes',
              },
              localChargesPerShipment: {
                value: 65,
                type: 'taxes',
              },
              localChargesHazardous: {
                value: 6,
                type: 'taxes',
              },
              localChargesFoodGrade: {
                value: 4,
                type: 'taxes',
              },
              customBrokerageImport: {
                value: null,
                type: 'taxes',
              },
              customBrokerageExport: {
                value: 567,
                type: 'taxes',
              },
              controlFeeForwarder: {
                value: 9,
                type: 'freight',
              },
              controlFeeAgent: {
                value: 909,
                type: 'freight',
              },
              tax: {
                value: 8,
                type: 'taxes',
              },
              sealineAirline: {
                value: 'MSC',
                type: 'info',
              },
              frequency: {
                value: null,
                type: 'info',
              },
              freeDaysAtDestination: {
                value: null,
                type: 'info',
              },
              notes: {
                value: null,
                type: 'info',
              },
              validity: {
                value: '2022-04-30T05:00:00.000Z',
                type: 'keyValue',
              },
              validityFrom: {
                value: '2022-04-01T05:00:00.000Z',
                type: 'keyValue',
              },
              tenantId: 'Rate-rokk3r',
              _id: '624c6236f39a4d0035ee4801',
              kind: 'ship FCL',
              showFreightSurchargesDetails: false,
              showTaxesDetails: false,
              extraFields: [],
              updatedAt: '2022-04-05T15:37:26.663Z',
              createdAt: '2022-04-05T15:37:26.663Z',
              __v: 0,
              line: {
                _id: '6019c700e3e6248a7fd73cae',
                name: 'MSC',
                type: 'carrier',
                group: 'sea',
                cursor: 360,
                logo: 'https://storage.googleapis.com/carriers_logos/msc-logo.png',
                logo2x:
                  'https://storage.googleapis.com/carriers_logos/msc-logo2x.png',
                __v: 0,
                createdAt: '2021-01-29T21:58:41.246Z',
                updatedAt: '2021-01-29T21:58:41.246Z',
                scac: ['MSCU', 'MEDU', 'MSCUAA', 'MEDUAA'],
              },
              freight: 927,
              freightSurcharges: 99,
              localCharges: 82.08,
              price: 1108.08,
            },
            quoteDetails: [
              {
                _id: '624c63dcf39a4d0035ee4937',
                sectionName: 'details',
                price: 1108.08,
                itemsData: [
                  {
                    _id: '624c63dcf39a4d0035ee4938',
                    price: 927,
                    item: 'Freight',
                    details: '',
                    USDprice: 927,
                  },
                  {
                    _id: '624c63dcf39a4d0035ee4939',
                    price: 99,
                    item: 'Freight Surcharges',
                    details: '',
                    USDprice: 99,
                  },
                  {
                    _id: '624c63dcf39a4d0035ee493a',
                    price: 82.08,
                    item: 'Shipment Fees',
                    details: '',
                    USDprice: 82.08,
                  },
                ],
                USDprice: 1108.08,
              },
            ],
            transitTimeFrecuency: 'days',
            transitTime: null,
            totalCost: 1108.08,
            carrier: {
              name: 'MSC',
            },
            USDtotalCost: 1108.08,
          },
          tags: ['active'],
          tenantId: 'Quote-rokk3r',
          companyId: '5e5893ef851e34004b7f954f',
          nameOfQuote: 'Clocks',
          quoteHash: '947bd558-6496-4774-afbf-ee90d115defc',
          commodity: 'Clock oscillators',
          commodityDescription: null,
          incoterms: 'FCA',
          transportationMode: 'ship',
          shipmentType: 'FCL',
          paymentTerms: 'prepaid',
          truckingService: 0,
          truckingServiceOption: null,
          truckingServiceOrigin: {
            pickupAddress: null,
          },
          truckingServiceDestiny: {
            deliveryAddress: null,
          },
          origin: 'Bern, Switzerland',
          destination: 'Nueva York, NY, USA',
          customBrokerage: 0,
          urgentShipment: 0,
          specialInstructions: null,
          portOrigin: null,
          portDestination: null,
          totalWeight: null,
          totalVolume: null,
          volumeType: 'm',
          weightType: 'kg',
          packagingData: [
            {
              amount: '1',
              volume: null,
              weight: null,
              totalVolume: null,
              totalWeight: null,
              lengthType: 'in',
              weightType: 'lb',
              hazardousMaterials: 0,
              hazardousDetails: [
                {
                  class: null,
                  subdivision: null,
                  group: null,
                  attach: null,
                },
              ],
              refrigeration: 0,
              containerType: "Dry 20'",
            },
          ],
          disclaimers: [
            {
              _id: '61d5a453b758410035c59806',
              title: 'v',
              description: 'f',
            },
            {
              _id: '61329d01a7df0d00355a1fb1',
              title: 'Blah!',
              description:
                "\nWhy do we use it?\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\n\n",
            },
            {
              _id: '60c395fd6edb4e0035cc45e2',
              title: 'Importaciones',
              description: 'Requiere contrato',
            },
          ],
          owner: {
            user: 'Jairo Internal',
            idUser: '5ea1b0cbb5775f01b50ac1e5',
            email: 'jairo.mendoza+rokk3r-ff@rokk3rlabs.com',
            typeUser: 'internal-owner',
            companyName: 'Rokk3r Clients',
            idCompany: '5e5893ef851e34004b7f954f',
          },
          accessorials: [],
          attachments: [],
          dimensionsPerPackage: [],
          __v: 0,
          assignData: {
            fromUser: {
              jobTitle: 'ceo',
              uid: '5ea1b0ca257713002656d92b',
              firstName: 'Jairo Internal',
              _id: '5ea1b0cbb5775f01b50ac1e5',
              email: 'jairo.mendoza+rokk3r-ff@rokk3rlabs.com',
            },
            user: {
              jobTitle: null,
              uid: '5ee33ad3c47179003a38b065',
              sendEmail: false,
              urlPhotoProfile:
                'https://storage.googleapis.com/development_app_files/rokk3r/profiles/b505b526-93c0-9922-3060-f5d809b2b780.jpg',
              firstName: 'Nata',
              _id: '5ee33ad356d39f0173524c2d',
              email: 'natalia.castellanos+rokk3r-ff-2@rokk3rlabs.com',
            },
            message: 'TYU',
            date: '2022-04-05T15:35:08.963Z',
            closeAssignDate: '2022-04-05T15:37:36.201Z',
            closeAssignMessage: '',
            internalAssigned: {
              jobTitle: 'ceo',
              uid: '5ea1b0ca257713002656d92b',
              sendEmail: true,
              firstName: 'Jairo Internal',
              _id: '5ea1b0cbb5775f01b50ac1e5',
              email: 'jairo.mendoza+rokk3r-ff@rokk3rlabs.com',
            },
          },
          confirmation: {
            aprovedBy: '5ea1b0cbb5775f01b50ac1e5',
            date: '2022-04-05T20:34:35.836Z',
            status: 'accept',
            fileId: '624ca7d9ebecd4002421e69d',
            description: 'ewrwerew',
          },
          clonedFrom: 'Q559-285_BERN-NUEVA_CLOCK_OSCILLATORS',
          status: 4,
          quoteId: 'Q562-285_BERN-NUEVA_CLOCK_OSCILLATORS',
          alterTags: {
            active: true,
          },
          updatedAt: '2022-04-05T20:34:35.911Z',
          createdAt: '2022-04-05T15:44:06.391Z',
          cursor: 910,
          trade: 'export',
          destinationDetails: {
            lng: 40.7127753,
            lat: -74.0059728,
            countryCode: 'US',
          },
          originDetails: {
            lng: 46.9479739,
            lat: 7.4474468,
            countryCode: 'CH',
          },
          createdDays: 92,
          company: 'rokk3r-clients',
        },
        accessorials: [],
        originDetails: {
          lat: 46.9479739,
          lng: 7.4474468,
          countryCode: 'CH',
        },
        destinationDetails: {
          lat: 40.7127753,
          lng: -74.0059728,
          countryCode: 'US',
        },
        owner: {
          user: 'Nata',
          idUser: '5ee33ad356d39f0173524c2d',
          email: 'natalia.castellanos+rokk3r-ff-2@rokk3rlabs.com',
          typeUser: 'internal-owner',
          companyName: 'Rokk3r Clients',
          idCompany: '5e5893ef851e34004b7f954f',
        },
        shipmentId: 'S562-285_BERN-NUEVA_CLOCK_OSCILLATORS-5',
        alterTags: {
          upcoming: true,
        },
        updatedAt: '2022-08-17T01:34:04.620Z',
        createdAt: '2022-07-22T15:03:02.746Z',
        cursor: 1971,
        __v: 0,
        commodity: 'Clock oscillators',
        incoterms: 'FCA',
        paymentTerms: 'prepaid',
        company: 'rokk3r-clients',
        cutoffDays: 68,
      },
      {
        _id: '633c5660f9b1a1003694b4d8',
        milestones: [
          'Origin',
          'Origin Customs Clearance',
          'ISF Filed',
          'Transit at Origin',
          'Port of Loading',
          'Port of Transshipment',
          'Port of Discharge',
          'Destination Customs Clearance',
          'Transit at Destination',
          'Container Return',
        ],
        tags: ['upcoming', 'quick'],
        tenantId: 'Shipment-rokk3r',
        trade: null,
        paymentTerms: 'collect',
        shipper: null,
        consignee: null,
        vesselNumber: null,
        voyageNumber: null,
        destination: 'Madrid, Spain',
        commodity: 'Cats',
        companyId: '5e5893ef851e34004b7f954f',
        manualInput: true,
        mbl: '',
        incoterms: 'FCA',
        confirmationNumber: '',
        flightNumber: '',
        referenceName: 'asdfa',
        etd: null,
        eta: null,
        containers: [
          {
            _id: '633c5660f9b1a1003694b4d9',
            id: '1',
            code: '1212',
          },
        ],
        notes: '',
        internalReference: '',
        freightType: 'ship',
        shipmentType: 'FCL',
        portOrigin: 'MC MON - Monaco',
        owner: {
          user: 'Nata Prueba',
          idUser: '5ee33ad356d39f0173524c2d',
          email: 'natalia.castellanos+rokk3r-ff-2@rokk3rlabs.com',
          typeUser: 'internal-owner',
          companyName: 'Rokk3r Clients',
          idCompany: '5e5893ef851e34004b7f954f',
        },
        totalWeight: null,
        totalVolume: null,
        volumeType: 'm',
        weightType: 'kg',
        packagingData: [
          {
            amount: '1',
            volume: '2',
            weight: '2',
            totalVolume: '2',
            totalWeight: '2',
            lengthType: 'm',
            weightType: 'kg',
            hazardousMaterials: 0,
            hazardousDetails: [],
            refrigeration: 0,
            containerType: "Dry 20'",
          },
        ],
        origin: 'MC MON - Monaco',
        destinationDetails: {
          lat: 40.4167754,
          lng: -3.7037902,
          countryCode: 'ES',
        },
        shipmentId: 'MS45-285_MCMON-MADRID_CATS',
        currentStatus: 'upcoming',
        alterTags: {
          upcoming: true,
        },
        originDetails: {
          lat: 43.73841760000001,
          lng: 7.424615799999999,
          countryCode: 'MC',
        },
        accessorials: [],
        attachments: [],
        updatedAt: '2022-10-04T15:50:56.783Z',
        createdAt: '2022-10-04T15:50:56.783Z',
        cursor: 2006,
        __v: 0,
        company: 'rokk3r-clients',
        cutoffDays: null,
      },
      {
        _id: '62fbeb07ae2f9b0599032c39',
        milestones: [
          'Origin',
          'Origin Customs Clearance',
          'ISF Filed',
          'Transit at Origin',
          'Port of Loading',
          'Port of Transshipment',
          'Port of Discharge',
          'Destination Customs Clearance',
          'Transit at Destination',
          'Container Return',
        ],
        tags: ['upcoming'],
        tenantId: 'Shipment-rokk3r',
        bookingId: 'B565-285_CHENNAI-CHICAGO_CATS',
        companyId: '5e5893ef851e34004b7f954f',
        referenceName: 'BBB',
        quoteId: '62fbc2f21f234f028da16c37',
        manualInput: true,
        fullName: '',
        shipper: '',
        consignee: '',
        agent: '',
        commodity: 'Cats',
        incoterms: 'FOB',
        shipmentType: 'FCL',
        freightType: 'ship',
        totalWeight: 0.9070294784580498,
        weightType: 'kg',
        origin: 'Chennai, Tamil Nadu, India',
        destination: 'Chicago, Illinois, USA',
        portOrigin: null,
        portDestination: null,
        currentStatus: 'upcoming',
        currentMilestone: 'Origin',
        attachments: [],
        containers: [],
        booking: {
          shipper: {
            name: '',
            address: '',
            email: '',
            phone: '',
          },
          notify: {
            name: '',
            address: '',
            email: '',
            phone: '',
          },
          consignee: {
            name: '',
            address: '',
            email: '',
            phone: '',
          },
          agent: {
            name: '',
            address: '',
            email: '',
            phone: '',
          },
          shipmentDetails: {
            transportationMode: 'ship',
            shipmentType: 'FCL',
            customBrokerage: 0,
            origin: 'Chennai, Tamil Nadu, India',
            destination: 'Chicago, Illinois, USA',
            portOrigin: null,
            portDestination: null,
            commodity: 'Cats',
            incoterms: 'FOB',
            totalWeight: 0.9070294784580498,
            totalVolume: 0.00003277399056109072,
            volumeType: 'm',
            weightType: 'kg',
            accessorials: [],
          },
          shippingInstructions: {
            containers: [],
          },
          tags: ['in progress'],
          tenantId: 'Booking-rokk3r',
          _id: '62fbeb07ae2f9b0599032c28',
          quoteId: '62fbc2f21f234f028da16c37',
          referenceName: 'BBB',
          dateRequested: '2022-08-16T19:07:50.572Z',
          companyId: '5e5893ef851e34004b7f954f',
          dateExpired: null,
          price: 12.04,
          quote: {
            confirmation: {
              aprovedBy: '5e5893f0851e34004b7f9551',
              date: '2022-08-16T19:07:50.501Z',
              status: 'accept',
            },
            quoteReply: {
              setPrice: {
                user: 'Nata Prueba',
                _id: '5ee33ad356d39f0173524c2d',
                date: '2022-08-16T19:07:11.420Z',
              },
              currency: 'USD',
              portOrigin: '',
              portDestination: '',
              validity: null,
              message: null,
              rate: {
                transportationMode: {
                  value: 'ship',
                  type: 'keyValue',
                },
                shipmentType: {
                  value: 'FCL',
                  type: 'keyValue',
                },
                commodity: {
                  value: 'Cats',
                  type: 'keyValue',
                },
                countryOrigin: {
                  value: null,
                  type: 'keyValue',
                },
                cityOrigin: {
                  value: 'Chennai, Tamil Nadu, India',
                  type: 'keyValue',
                },
                countryDestination: {
                  value: null,
                  type: 'keyValue',
                },
                cityDestination: {
                  value: 'Chicago, Illinois, USA',
                  type: 'keyValue',
                },
                portOrigin: {
                  value: null,
                  type: 'keyValue',
                },
                portDestination: {
                  value: null,
                  type: 'keyValue',
                },
                twenty: {
                  value: 1,
                  type: 'freight',
                },
                fourty: {
                  value: 1,
                  type: 'freight',
                },
                fourtyFive: {
                  value: 1,
                  type: 'freight',
                },
                fourtyHC: {
                  value: 1,
                  type: 'freight',
                },
                fourtyRF: {
                  value: 1,
                  type: 'freight',
                },
                fourtyNOR: {
                  value: 1,
                  type: 'freight',
                },
                tho: {
                  value: 1,
                  type: 'freightSurcharges',
                },
                thd: {
                  value: 1,
                  type: 'freightSurcharges',
                },
                fob: {
                  value: 1,
                  type: 'freightSurcharges',
                },
                tt: {
                  value: '1',
                  type: 'info',
                },
                ebs: {
                  value: 1,
                  type: 'freightSurcharges',
                },
                transhipment: {
                  value: '1',
                  type: 'info',
                },
                prepaidPerContainer: {
                  value: 1,
                  type: 'taxes',
                },
                collectPerContainer: {
                  value: 1,
                  type: 'taxes',
                },
                localChargesPerShipment: {
                  value: 1,
                  type: 'taxes',
                },
                localChargesHazardous: {
                  value: 1,
                  type: 'taxes',
                },
                localChargesFoodGrade: {
                  value: 1,
                  type: 'taxes',
                },
                customBrokerageImport: {
                  value: 1,
                  type: 'taxes',
                },
                customBrokerageExport: {
                  value: 1,
                  type: 'taxes',
                },
                controlFeeForwarder: {
                  value: 1,
                  type: 'freight',
                },
                controlFeeAgent: {
                  value: 1,
                  type: 'freight',
                },
                tax: {
                  value: 1,
                  type: 'taxes',
                },
                sealineAirline: {
                  value: 'ADNATCO',
                  type: 'info',
                },
                frequency: {
                  value: 'daily',
                  type: 'info',
                },
                freeDaysAtDestination: {
                  value: '1',
                  type: 'info',
                },
                notes: {
                  value: '1',
                  type: 'info',
                },
                validity: {
                  value: '2022-08-31T05:00:00.000Z',
                  type: 'keyValue',
                },
                validityFrom: {
                  value: '2022-08-01T05:00:00.000Z',
                  type: 'keyValue',
                },
                tenantId: 'Rate-rokk3r',
                _id: '62fbeabf9d3aac00366c1cb4',
                kind: 'ship FCL',
                showFreightSurchargesDetails: false,
                showTaxesDetails: false,
                extraFields: [],
                updatedAt: '2022-08-16T19:06:39.239Z',
                createdAt: '2022-08-16T19:06:39.239Z',
                __v: 0,
                line: {
                  _id: '6019c700e3e6248a7fd73d02',
                  name: 'ADNATCO',
                  type: 'carrier',
                  group: 'sea',
                  cursor: 443,
                  __v: 0,
                  createdAt: '2021-01-29T21:58:41.246Z',
                  updatedAt: '2021-01-29T21:58:41.246Z',
                },
                freight: 4,
                freightSurcharges: 4,
                localCharges: 4.04,
                price: 12.04,
              },
              quoteDetails: [
                {
                  _id: '62fbeae39d3aac00366c1cd5',
                  sectionName: 'details',
                  price: 12.04,
                  itemsData: [
                    {
                      _id: '62fbeae39d3aac00366c1cd6',
                      price: 4,
                      item: 'Freight',
                      details: '',
                      USDprice: 4,
                    },
                    {
                      _id: '62fbeae39d3aac00366c1cd7',
                      price: 4,
                      item: 'Freight Surcharges',
                      details: '',
                      USDprice: 4,
                    },
                    {
                      _id: '62fbeae39d3aac00366c1cd8',
                      price: 4.04,
                      item: 'Shipment Fees',
                      details: '',
                      USDprice: 4.04,
                    },
                  ],
                  USDprice: 12.04,
                },
              ],
              transitTimeFrecuency: 'days',
              transitTime: '1',
              totalCost: 12.04,
              carrier: {
                name: 'ADNATCO',
              },
              USDtotalCost: 12.04,
              portOfTranshipment: [],
            },
            tags: ['active'],
            tenantId: 'Quote-rokk3r',
            _id: '62fbc2f21f234f028da16c37',
            companyId: '5e5893ef851e34004b7f954f',
            nameOfQuote: 'BBB',
            quoteHash: '8f2c0e0d-eb27-45cd-889d-27d3166d9914',
            commodity: 'Cats',
            commodityDescription: null,
            incoterms: 'FOB',
            transportationMode: 'ship',
            shipmentType: 'FCL',
            paymentTerms: 'collect',
            truckingService: 0,
            truckingServiceOption: null,
            truckingServiceOrigin: {
              pickupAddress: null,
              deliveryAddress: null,
            },
            truckingServiceDestiny: {
              pickupAddress: null,
              deliveryAddress: null,
            },
            origin: 'Chennai, Tamil Nadu, India',
            destination: 'Chicago, Illinois, USA',
            portOrigin: null,
            portDestination: null,
            departureDate: null,
            customBrokerage: 0,
            urgentShipment: 0,
            specialInstructions: null,
            totalWeight: 0.9070294784580498,
            totalVolume: 0.00003277399056109072,
            volumeType: 'm',
            weightType: 'kg',
            packagingData: [
              {
                amount: '2',
                volume: '2',
                weight: '2',
                totalVolume: '2',
                totalWeight: '2',
                lengthType: 'in',
                weightType: 'lb',
                hazardousMaterials: 0,
                hazardousDetails: [],
                refrigeration: 0,
                containerType: "Dry 20'",
              },
            ],
            disclaimers: [
              {
                _id: '61d5add9b758410035c59807',
                title: 'cc',
                description: 'dd',
              },
              {
                _id: '61d5a453b758410035c59806',
                title: 'v',
                description: 'f',
              },
              {
                _id: '61329d01a7df0d00355a1fb1',
                title: 'Blah!',
                description:
                  "\nWhy do we use it?\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\n\n",
              },
              {
                _id: '60c395fd6edb4e0035cc45e2',
                title: 'Importaciones',
                description: 'Requiere contrato',
              },
            ],
            status: 3,
            alterTags: {
              active: true,
            },
            owner: {
              user: 'Pedro',
              idUser: '629f82ba92a9cc0036c4fd3d',
              email: 'dropeholguin1994+cldev@gmail.com',
              typeUser: 'internal',
              companyName: 'Rokk3r Clients',
              idCompany: '5e5893ef851e34004b7f954f',
            },
            quoteId: 'Q565-285_CHENNAI-CHICAGO_CATS',
            accessorials: [],
            attachments: [],
            dimensionsPerPackage: [],
            updatedAt: '2022-08-16T19:07:50.521Z',
            createdAt: '2022-08-16T16:16:50.188Z',
            cursor: 948,
            __v: 0,
            assignData: {
              fromUser: {
                jobTitle: 'Developer',
                uid: '629f82ba421cb900181b814d',
                urlPhotoProfile:
                  'https://storage.googleapis.com/development_app_files/rokk3r/profiles/10b15660-074c-fd21-cc1c-59826d172bfb.png',
                firstName: 'Pedro',
                _id: '629f82ba92a9cc0036c4fd3d',
                email: 'dropeholguin1994+cldev@gmail.com',
              },
              user: {
                uid: '5ee33ad3c47179003a38b065',
                firstName: 'Nata Prueba',
                _id: '5ee33ad356d39f0173524c2d',
                email: 'natalia.castellanos+rokk3r-ff-2@rokk3rlabs.com',
              },
              message: 'urgente',
              date: '2022-08-16T16:16:50.744Z',
            },
          },
          packagingData: [
            {
              amount: '2',
              volume: '2',
              weight: '2',
              totalVolume: '2',
              totalWeight: '2',
              lengthType: 'in',
              weightType: 'lb',
              hazardousMaterials: 0,
              hazardousDetails: [],
              refrigeration: 0,
              containerType: "Dry 20'",
            },
          ],
          owner: {
            user: 'Pedro',
            idUser: '629f82ba92a9cc0036c4fd3d',
            email: 'dropeholguin1994+cldev@gmail.com',
            typeUser: 'internal',
            companyName: 'Rokk3r Clients',
            idCompany: '5e5893ef851e34004b7f954f',
          },
          status: 'inProgress',
          alterTags: {
            'in progress': true,
          },
          USDprice: 12.04,
          bookingId: 'B565-285_CHENNAI-CHICAGO_CATS',
          history: {
            shipmentDetails: {
              accessorials: [
                {
                  previousValue: [],
                  currentValue: [],
                  time: '2022-08-16T19:07:51.520Z',
                  updatedBy: {
                    email: 'jesus.duarte+rokk3r-client2@rokk3rlabs.com',
                    firstName: 'Jesus Rokk3r Client2',
                    _id: '5e5893f0851e34004b7f9551',
                    uid: '5e5893f07d633800188aba31',
                  },
                },
              ],
            },
            packagingData: {
              'hazardousDetails-1': [
                {
                  previousValue: [],
                  currentValue: [],
                  time: '2022-08-16T19:07:51.520Z',
                  updatedBy: {
                    email: 'jesus.duarte+rokk3r-client2@rokk3rlabs.com',
                    firstName: 'Jesus Rokk3r Client2',
                    _id: '5e5893f0851e34004b7f9551',
                    uid: '5e5893f07d633800188aba31',
                  },
                },
              ],
            },
          },
          priceBreakdown: [],
          attachments: [],
          updatedAt: '2022-08-16T19:07:51.526Z',
          createdAt: '2022-08-16T19:07:51.526Z',
          cursor: 420,
          __v: 0,
        },
        quote: {
          confirmation: {
            aprovedBy: '5e5893f0851e34004b7f9551',
            date: '2022-08-16T19:07:50.501Z',
            status: 'accept',
          },
          quoteReply: {
            setPrice: {
              user: 'Nata Prueba',
              _id: '5ee33ad356d39f0173524c2d',
              date: '2022-08-16T19:07:11.420Z',
            },
            currency: 'USD',
            portOrigin: '',
            portDestination: '',
            validity: null,
            message: null,
            rate: {
              transportationMode: {
                value: 'ship',
                type: 'keyValue',
              },
              shipmentType: {
                value: 'FCL',
                type: 'keyValue',
              },
              commodity: {
                value: 'Cats',
                type: 'keyValue',
              },
              countryOrigin: {
                value: null,
                type: 'keyValue',
              },
              cityOrigin: {
                value: 'Chennai, Tamil Nadu, India',
                type: 'keyValue',
              },
              countryDestination: {
                value: null,
                type: 'keyValue',
              },
              cityDestination: {
                value: 'Chicago, Illinois, USA',
                type: 'keyValue',
              },
              portOrigin: {
                value: null,
                type: 'keyValue',
              },
              portDestination: {
                value: null,
                type: 'keyValue',
              },
              twenty: {
                value: 1,
                type: 'freight',
              },
              fourty: {
                value: 1,
                type: 'freight',
              },
              fourtyFive: {
                value: 1,
                type: 'freight',
              },
              fourtyHC: {
                value: 1,
                type: 'freight',
              },
              fourtyRF: {
                value: 1,
                type: 'freight',
              },
              fourtyNOR: {
                value: 1,
                type: 'freight',
              },
              tho: {
                value: 1,
                type: 'freightSurcharges',
              },
              thd: {
                value: 1,
                type: 'freightSurcharges',
              },
              fob: {
                value: 1,
                type: 'freightSurcharges',
              },
              tt: {
                value: '1',
                type: 'info',
              },
              ebs: {
                value: 1,
                type: 'freightSurcharges',
              },
              transhipment: {
                value: '1',
                type: 'info',
              },
              prepaidPerContainer: {
                value: 1,
                type: 'taxes',
              },
              collectPerContainer: {
                value: 1,
                type: 'taxes',
              },
              localChargesPerShipment: {
                value: 1,
                type: 'taxes',
              },
              localChargesHazardous: {
                value: 1,
                type: 'taxes',
              },
              localChargesFoodGrade: {
                value: 1,
                type: 'taxes',
              },
              customBrokerageImport: {
                value: 1,
                type: 'taxes',
              },
              customBrokerageExport: {
                value: 1,
                type: 'taxes',
              },
              controlFeeForwarder: {
                value: 1,
                type: 'freight',
              },
              controlFeeAgent: {
                value: 1,
                type: 'freight',
              },
              tax: {
                value: 1,
                type: 'taxes',
              },
              sealineAirline: {
                value: 'ADNATCO',
                type: 'info',
              },
              frequency: {
                value: 'daily',
                type: 'info',
              },
              freeDaysAtDestination: {
                value: '1',
                type: 'info',
              },
              notes: {
                value: '1',
                type: 'info',
              },
              validity: {
                value: '2022-08-31T05:00:00.000Z',
                type: 'keyValue',
              },
              validityFrom: {
                value: '2022-08-01T05:00:00.000Z',
                type: 'keyValue',
              },
              tenantId: 'Rate-rokk3r',
              _id: '62fbeabf9d3aac00366c1cb4',
              kind: 'ship FCL',
              showFreightSurchargesDetails: false,
              showTaxesDetails: false,
              extraFields: [],
              updatedAt: '2022-08-16T19:06:39.239Z',
              createdAt: '2022-08-16T19:06:39.239Z',
              __v: 0,
              line: {
                _id: '6019c700e3e6248a7fd73d02',
                name: 'ADNATCO',
                type: 'carrier',
                group: 'sea',
                cursor: 443,
                __v: 0,
                createdAt: '2021-01-29T21:58:41.246Z',
                updatedAt: '2021-01-29T21:58:41.246Z',
              },
              freight: 4,
              freightSurcharges: 4,
              localCharges: 4.04,
              price: 12.04,
            },
            quoteDetails: [
              {
                _id: '62fbeae39d3aac00366c1cd5',
                sectionName: 'details',
                price: 12.04,
                itemsData: [
                  {
                    _id: '62fbeae39d3aac00366c1cd6',
                    price: 4,
                    item: 'Freight',
                    details: '',
                    USDprice: 4,
                  },
                  {
                    _id: '62fbeae39d3aac00366c1cd7',
                    price: 4,
                    item: 'Freight Surcharges',
                    details: '',
                    USDprice: 4,
                  },
                  {
                    _id: '62fbeae39d3aac00366c1cd8',
                    price: 4.04,
                    item: 'Shipment Fees',
                    details: '',
                    USDprice: 4.04,
                  },
                ],
                USDprice: 12.04,
              },
            ],
            transitTimeFrecuency: 'days',
            transitTime: '1',
            totalCost: 12.04,
            carrier: {
              name: 'ADNATCO',
            },
            USDtotalCost: 12.04,
            portOfTranshipment: [],
          },
          tags: ['active'],
          tenantId: 'Quote-rokk3r',
          _id: '62fbc2f21f234f028da16c37',
          companyId: '5e5893ef851e34004b7f954f',
          nameOfQuote: 'BBB',
          quoteHash: '8f2c0e0d-eb27-45cd-889d-27d3166d9914',
          commodity: 'Cats',
          commodityDescription: null,
          incoterms: 'FOB',
          transportationMode: 'ship',
          shipmentType: 'FCL',
          paymentTerms: 'collect',
          truckingService: 0,
          truckingServiceOption: null,
          truckingServiceOrigin: {
            pickupAddress: null,
            deliveryAddress: null,
          },
          truckingServiceDestiny: {
            pickupAddress: null,
            deliveryAddress: null,
          },
          origin: 'Chennai, Tamil Nadu, India',
          destination: 'Chicago, Illinois, USA',
          portOrigin: null,
          portDestination: null,
          departureDate: null,
          customBrokerage: 0,
          urgentShipment: 0,
          specialInstructions: null,
          totalWeight: 0.9070294784580498,
          totalVolume: 0.00003277399056109072,
          volumeType: 'm',
          weightType: 'kg',
          packagingData: [
            {
              amount: '2',
              volume: '2',
              weight: '2',
              totalVolume: '2',
              totalWeight: '2',
              lengthType: 'in',
              weightType: 'lb',
              hazardousMaterials: 0,
              hazardousDetails: [],
              refrigeration: 0,
              containerType: "Dry 20'",
            },
          ],
          disclaimers: [
            {
              _id: '61d5add9b758410035c59807',
              title: 'cc',
              description: 'dd',
            },
            {
              _id: '61d5a453b758410035c59806',
              title: 'v',
              description: 'f',
            },
            {
              _id: '61329d01a7df0d00355a1fb1',
              title: 'Blah!',
              description:
                "\nWhy do we use it?\nIt is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).\n\n",
            },
            {
              _id: '60c395fd6edb4e0035cc45e2',
              title: 'Importaciones',
              description: 'Requiere contrato',
            },
          ],
          status: 3,
          alterTags: {
            active: true,
          },
          owner: {
            user: 'Pedro',
            idUser: '629f82ba92a9cc0036c4fd3d',
            email: 'dropeholguin1994+cldev@gmail.com',
            typeUser: 'internal',
            companyName: 'Rokk3r Clients',
            idCompany: '5e5893ef851e34004b7f954f',
          },
          quoteId: 'Q565-285_CHENNAI-CHICAGO_CATS',
          accessorials: [],
          attachments: [],
          dimensionsPerPackage: [],
          updatedAt: '2022-08-16T19:07:50.521Z',
          createdAt: '2022-08-16T16:16:50.188Z',
          cursor: 948,
          __v: 0,
          assignData: {
            fromUser: {
              jobTitle: 'Developer',
              uid: '629f82ba421cb900181b814d',
              urlPhotoProfile:
                'https://storage.googleapis.com/development_app_files/rokk3r/profiles/10b15660-074c-fd21-cc1c-59826d172bfb.png',
              firstName: 'Pedro',
              _id: '629f82ba92a9cc0036c4fd3d',
              email: 'dropeholguin1994+cldev@gmail.com',
            },
            user: {
              uid: '5ee33ad3c47179003a38b065',
              firstName: 'Nata Prueba',
              _id: '5ee33ad356d39f0173524c2d',
              email: 'natalia.castellanos+rokk3r-ff-2@rokk3rlabs.com',
            },
            message: 'urgente',
            date: '2022-08-16T16:16:50.744Z',
          },
        },
        accessorials: [],
        originDetails: {
          lat: 13.0826802,
          lng: 80.2707184,
          countryCode: 'IN',
        },
        destinationDetails: {
          lat: 41.8781136,
          lng: -87.6297982,
          countryCode: 'US',
        },
        owner: {
          user: 'Pedro',
          idUser: '629f82ba92a9cc0036c4fd3d',
          email: 'dropeholguin1994+cldev@gmail.com',
          typeUser: 'internal',
          companyName: 'Rokk3r Clients',
          idCompany: '5e5893ef851e34004b7f954f',
        },
        shipmentId: 'S565-285_CHENNAI-CHICAGO_CATS',
        alterTags: {
          upcoming: true,
        },
        updatedAt: '2022-08-18T21:17:33.946Z',
        createdAt: '2022-08-16T19:07:51.801Z',
        cursor: 1975,
        __v: 0,
        etd: '2022-08-16T05:00:00.000Z',
        eta: '2022-08-24T05:00:00.000Z',
        automaticEvents: false,
        mbl: 'HHH2323',
        carrier: {
          name: 'ADNATCO',
        },
        paymentTerms: 'collect',
        company: 'rokk3r-clients',
        cutoffDays: null,
      },
    ];
  }

  dropRow(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.paginateData, event.previousIndex, event.currentIndex);
  }
  dropCol(event: CdkDragDrop<string[]>) {
    moveItemInArray(this.columns, event.previousIndex, event.currentIndex);
    console.log(this.columns, this.paginateData);
  }
  mouseDown(event, el: any = null) {
    el = el || event.target;
    this.pos = {
      x: el.getBoundingClientRect().left - event.clientX + 'px',
      y: el.getBoundingClientRect().top - event.clientY + 'px',
      width: el.getBoundingClientRect().width + 'px',
    };
  }
  onDragRelease(event: CdkDragRelease) {
    this.renderer2.setStyle(
      event.source.element.nativeElement,
      'margin-left',
      '0px'
    );
  }
}
